### ISSUE TITLE
fastboot: error: Could not check if partition recovery has slot all

### ISSUE THREAD

**Issue by cavv-dev** [chickendrop89/device_xiaomi_sm6225ad-recovery#4]
Fastboot gives error with command `fastboot flash recovery out/target/product/tapas/recovery.img --slot=all`:

`fastboot: error: Could not check if partition recovery has slot all`
![2023-12-28 22_20_18-C__Windows_System32_cmd exe](https://github.com/chickendrop89/orangefox_device_xiaomi_tapas/assets/65863280/bc9fec90-cddb-456f-9477-8d3f6e22043d)

**Comment by chkndrp** [comment]
I have noticed using the `--slot=all` switch works only in userspace fastboot because, on this device, [traditional bootloader is missing the `has-slot` variable](https://android.googlesource.com/platform/system/core/+/2ec418a4c98f6e8f95395456e1ad4c2956cac007/fastboot/fastboot.cpp#862) thus it throws this error

Use these commands instead:
`fastboot flash recovery_a OrangeFox-Unofficial-tapas.img`
`fastboot flash recovery_b OrangeFox-Unofficial-tapas.img`


I will update the readmes and stuff, thanks for telling me!
